# Generated by Django 4.2.1 on 2023-06-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppCoder", "0002_entregable_estudiante_profesor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Articulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=40)),
                ("subtitulo", models.CharField(max_length=300)),
                ("contenido", models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name="Autor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=40)),
                ("apellido", models.CharField(max_length=20)),
                ("usuario", models.CharField(max_length=30)),
                ("contraseña", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=40)),
                ("apellido", models.CharField(max_length=20)),
                ("usuario", models.CharField(max_length=30)),
                ("contraseña", models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name="Entregable",
        ),
        migrations.DeleteModel(
            name="Estudiante",
        ),
        migrations.DeleteModel(
            name="Profesor",
        ),
    ]
