# Generated by Django 4.2.1 on 2023-06-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppCoder", "0003_articulo_autor_usuario_delete_entregable_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="autor",
            name="profesion",
            field=models.CharField(default="Periodista", max_length=30),
        ),
    ]
