# Generated by Django 4.2.1 on 2023-06-07 14:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("AppCoder", "0004_autor_profesion"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Curso",
        ),
    ]
